require("core.plugin_config.mason")
require("core.plugin_config.colorscheme")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.treesitter")
require("core.plugin_config.telescope")
require("core.plugin_config.vim-test")
require("core.plugin_config.completions")
require("core.plugin_config.lsp_config")
require("core.plugin_config.gitsigns")
-- require("core.plugin_config.rust_config")
-- require("core.plugin_config.dap_config")
require("core.plugin_config.nvim_terminal")
require("core.plugin_config.bufferline")
require("core.plugin_config.zen-mode")
require("core.plugin_config.prettier")
require("core.plugin_config.null-ls")
require("core.plugin_config.lspkind")
require("core.plugin_config.ts-autotag")
require("core.plugin_config.formattear")
